# Generated by Django 5.0.2 on 2025-10-14 10:24

import django_quill.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DietryNeeds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(upload_to='blogs/thumbnails/')),
                ('image', models.ImageField(upload_to='blogs/images/')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('content', django_quill.fields.QuillField()),
                ('category', models.ManyToManyField(related_name='blogs', to='kathiyawadApi.blogcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/images/')),
                ('title', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=50)),
                ('metaDescription', models.CharField(max_length=300)),
                ('description', django_quill.fields.QuillField()),
                ('ingredients', django_quill.fields.QuillField()),
                ('shippingAndDelivery', django_quill.fields.QuillField()),
                ('dietryNeeds', models.ManyToManyField(related_name='products', to='kathiyawadApi.dietryneeds')),
                ('relatedProducts', models.ManyToManyField(blank=True, to='kathiyawadApi.product')),
                ('category', models.ManyToManyField(related_name='products', to='kathiyawadApi.productcategory')),
            ],
        ),
    ]
